#!/usr/bin/env bash
cd data/classification/
wget https://www.dropbox.com/sh/fni72jye2xx1n7f/config.yaml
wget https://www.dropbox.com/sh/8ey299wr0n9927o/char.pkl
wget https://www.dropbox.com/sh/7y5a6vhycfyxdcd/word.pkl
wget https://www.dropbox.com/sh/eu5jx5nf2l5gq0m/test.csv
wget https://www.dropbox.com/sh/qn5k4uzr211nx02/test.pkl
cd ..
cd ..
cd model/submission/ckpts/
wget https://www.dropbox.com/sh/7mbzp4swh1ds6rq/epoch-9.ckpt
wget https://www.dropbox.com/sh/uglvnh5uji4s9fk/epoch-3.ckpt
wget https://www.dropbox.com/sh/jhdqi251ahj22j8/epoch-4.ckpt
cd ..
wget https://www.dropbox.com/sh/9o6i4cfoagh4cl6/config.yaml
cd ..
cd ..
cd ELMo/configs/
wget https://www.dropbox.com/sh/yzdj6jkw84uu45c/cnn_50_100_512_4096_sample.json
cd ..
cd output/
wget https://www.dropbox.com/sh/gn9jb0kijyoekl1/char.dic
wget https://www.dropbox.com/sh/we44v7iolb2txin/word.dic
wget https://www.dropbox.com/sh/1pxgfrpqep7q0sq/config.json
wget https://www.dropbox.com/sh/zfy8d4rnrskoh87/encoder.pkl
wget https://www.dropbox.com/sh/dpg1qoevrt61gi3/token_embedder.pkl
cd ..
cd ..