#!/usr/bin/env bash
cd code/data/classification/
wget https://www.dropbox.com/s/5oopej3dp5qs513/config.yaml
wget https://www.dropbox.com/s/3s5p7aq2lr8it3o/char.pkl
wget https://www.dropbox.com/s/hdi4t1qfb9hd6sc/word.pkl
wget https://www.dropbox.com/s/m05mzjj935rkx04/test.csv
cd ..
cd model/MODEL_NAME/ckpts/
wget https://www.dropbox.com/s/mwvlv8y5c3463c5/predict1.ckpt
wget https://www.dropbox.com/s/6caun6du9e0s2v8/predict2.ckpt
wget https://www.dropbox.com/s/wricxnsho0vdqk3/predict3.ckpt
wget https://www.dropbox.com/s/ntjsnll92bk1z9h/predict4.ckpt
wget https://www.dropbox.com/s/7q0iwgzijw99vcb/predict5.ckpt
wget https://www.dropbox.com/s/ebk9f3p1myi9rd4/predict6.ckpt
wget https://www.dropbox.com/s/6jm00d9rtm5ad47/predict7.ckpt
cd ..
wget https://www.dropbox.com/s/rqdi040bovi2bq5/config1.yaml
wget https://www.dropbox.com/s/3h3iuis7cj88hib/config2.yaml
wget https://www.dropbox.com/s/ugt6f1rbhy2ryaa/config3.yaml
wget https://www.dropbox.com/s/yi2ucv6kh2uwvu2/config4.yaml
wget https://www.dropbox.com/s/aop14kadck5rzc9/config5.yaml
wget https://www.dropbox.com/s/cx0725kvsr6w38l/config6.yaml
wget https://www.dropbox.com/s/thzrd5jnmollasx/config7.yaml
cd ..
cd ..
cd ..
cd ..